### ISSUE TITLE
Converting 8088 Depackers to x86

### ISSUE THREAD

**Issue by odzhan** [emmanuel-marty/apultra#5]
Hi,

Having problems converting the small 8088 depacker to x86. For an EXE file of 814232 bytes, it fails to decode file after processing 811240 bytes. It works fine with smaller files, so have you any suggestions on how to fix it?

[aplib_x86_small.asm.zip](https://github.com/emmanuel-marty/apultra/files/4636822/aplib_x86_small.asm.zip)

**Comment by emmanuel-marty** [comment]
From a first glance, the most likely issue is that you aren't handling offsets >= 64K. You kept the 'mov dh,cl' on line 97 which will only copy 8 high bits, which means the offsets will still be limited to < 64K. You should probably do something like mov edx, ecx / shl ecx,8 . Same with the minmatch 3/4 offset comparisons below, the cmp dh,07DH should be a cmp edx,07D00H, cmp dh,05H should be cmp edx,0500H and cmp dx,0080H a cmp edx,80H (or equivalent shorter code forms). 

I will look further and do some tests, but that would be my first guess!

Note that you can limit the max offsets by using -w 65535 or somesuch on the apultra command line, just for quickly testing if the offset sizes are the issue. I wouldn't recommend actually using that in production, as it would grealy limit compression of your large exes, but just for testing.

**Comment by emmanuel-marty** [comment]
Ok, the code below seems to work with large files (I took your code and put in the changes in my previous message, plus a xor edx,edx instead of dh,dh in the code handling 7O+1M commands). If you optimize for size there are probably some opportunities to reduce this down. Let me know if that works :)

[aplib_x86_small_fixed.zip](https://github.com/emmanuel-marty/apultra/files/4638227/aplib_x86_small_fixed.zip)

**Comment by odzhan** [comment]
Thanks for the prompt response and help. It appears to be working fine now! :)
